### ISSUE TITLE
Improve compute_worker.py - Dataset submission bundle stuck at scoring sometimes

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1011]
### TODOs

- [x] Re-organize the code of compute_worker.py and add comments to each function and tricky parts to make the code clearer.
- [x] Wrap everything in try/catch to catch every error
- [x] Fix the size / timing problem with ingestion outputing big files (see symptoms below) (#1130)

### Related problems: 
- [ ] No logs when compute worker crashes (https://github.com/codalab/codabench/issues/902) 
- [x] We need to show the hostname of scoring job in server status (https://github.com/codalab/codabench/issues/744)

### Symptoms

- Submission stuck at scoring
- `BadZipFile` error in the compute worker when trying to unpack the output from ingestion program

Examples are given below.

### Lisheng's bundle

Lisheng's bundle, which is a modified Mini-AutoML with dataset submission, is sometimes stuck at scoring.

What we have investigated:

- If there is only one worker in the queue, then it works fine
- If there are multiple workers in the queue (default queue), then we have the problem, and we get this error message:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in _protected_call_
    return self.run(*args, **kwargs)
  File "/compute_worker.py", line 91, in run_wrapper
    run.prepare()
  File "/compute_worker.py", line 655, in prepare
    zip_file = self._get_bundle(url, path, cache=cache_this_bundle)
  File "/compute_worker.py", line 363, in _get_bundle
    with ZipFile(bundle_file, 'r') as z:
  File "/usr/local/lib/python3.8/zipfile.py", line 1269, in _init_
    self._RealGetContents()
  File "/usr/local/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Another possibility is that the restarting of the worker is what solved the issue for the new queue.

### L2RPN

It seems that uploading/downloading the ingestion output is what is failing.

https://github.com/codalab/codabench/blob/fbaa97444cfd92747cd00fa189bb1c67614d15e7/compute_worker/compute_worker.py#L363C1-L365C67

The same issue is happening with the Sim2Real track of L2RPN 2023.
The saved agent, passed from ingestion to scoring, weights 5GB.
**I confirm that the problem does not happen when we do not save the 5GB file. It is a problem of size and timing.**

Hypothesis: as ingestion and scoring runs in parallel, maybe the scoring is trying to download and unpack the output from ingestion too early. The file is still not completely saved and zipped when the scoring is downloading it. When we try to same URL later, it is working fine.

**Comment by Didayolo** [comment]
The same issue is happening with the Sim2Real track of L2RPN 2023.

**Comment by ihsaan-ullah** [comment]
In normal cases, we want the ingestion to run first and then the scoring. Can we make changes to the compute worker to do things in a pipeline i.e. when a submission is forwarded to the compute worker,  do the following in proper order
1. Get submission and unpack files
2. Run ingestion program and store results in temp dir (Or pass this step if no ingestion program)
3. Run scoring program and store results and show on leaderboard 

Note: right now it looks like, ingestion and scoring are two separate tasks and can be run on different workers. 

Current computer worker code is done in a complicated way. It should be made simple are easy to understand. Also every thing should be wrapped in try catch to catch every error. We have some problems where scoring program error logs are not shown.

**Comment by Didayolo** [comment]
Should we check integrity after having downloaded the bundle?

```python
def _get_bundle(self, url, destination, cache=True):
    
    # [...] (existing code)
    # Download the bundle...

    # Check integrity here
    
    with ZipFile(bundle_file, 'r') as z:
        z.extractall(os.path.join(self.root_dir, destination))
```

**Comment by Didayolo** [comment]
> > Maybe the first step is to re-organize the code of compute_worker.py and add comments to each function and tricky parts to make the code clearer.
> 
> This should be a P1 issue

I edited this issue to include these points

**Comment by Didayolo** [comment]
Currently testing this change:

https://github.com/codalab/codabench/commit/d5620c95471628427fee4a03a28eeb414f81e9c9

**Comment by Didayolo** [comment]
We can see simultaneously this on the ingestion worker:

<img width="1435" alt="Capture d’écran 2023-09-01 à 18 53 17" src="https://github.com/codalab/codabench/assets/11784999/f0575efd-828f-42b1-b1c9-d5d529c9106a">


and this in the scoring worker:

<img width="1440" alt="Capture d’écran 2023-09-01 à 18 53 24" src="https://github.com/codalab/codabench/assets/11784999/a1865a95-f92b-445d-a2e6-2dd017b9ac5d">

So indeed, the download starts during the uploading, asynchronously.
