### ISSUE TITLE
Performance problem - Pages are too slow to load

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1327]
Codabench is too slow to load.

- Home page of competitions are loading everything at once. We need a lazy loading.

- When a loading is long, it is decreasing the performance for everybody else (this is normal I guess).

- Competitions list is slow to load too, despite the small logos (#1290). Code of this page: https://github.com/codalab/codabench/blob/f83f94c1e492da524fef5b2f6ccf26846fa88b69/src/static/riot/competitions/public-list.tag

### TODO

- [x] Increase the CPU and RAM of the main VM
- [x] Increase the CPU and RAM of the main VM (again)
- [ ] **Competition page**
  - [x] Trying to remove "entries" column from leaderboard, which may be the one that is slow to load (#1673)
  - [ ] Put back "entries" in an efficient way
  - [ ] Pagination for "Submissions" tab (and lazy loading)
  - [x] ~"Show more" on leaderboard results tab. By default show 30 rows, and add more when clicking on show more. If the participants is not on the first 30, it could still be shown at the bottom of the table after some "[...]" row~
- [ ] **Competition list**
  - [x] Optimize the code for loading the competitions list (@bbearce) (#1376) (#1381)
  - [ ] #1381 improves the query by directly filter public competitions. We need to improve the filter to take into account the dates and page of the public list we are displaying.
- [x] **General performance and home page**
  - [x] Remove temporarily participants and submissions counters to accelerate the competition loading #1645
  - [x] Participants and submissions counters in an efficient way (#1669)
  - [x] Featured competitions manually set (#1678)
  - [x] Home page counters (#1699)
    - [x] Update the counts somewhere in a file or in the db with a script that is run once a day
    - [x] Update home page to fetch the counts from the file/db to make them dynamic instead of hardcoded

**Comment by ihsaan-ullah** [comment]
> * [ ]  Optimize the code for loading a competition page

This needs proper planning as code cannot be optimized with current structure of the web page. It is a big update

**Comment by Didayolo** [comment]
Still very slow after merging #1343

**Comment by bbearce** [comment]
Tested and think I have a fix:
[Docs for automation to create large amounts of data](https://github.com/codalab/codabench/wiki/Automating-with-Selenium)

Essentially we used the CompetitionDetailSerializer to load competitions and I switched to CompetitionSerializerSimple. The detail one serializes phases and tasks and I believe that is time consuming. The Simple one has everything we need and it loads things faster on my local when I create lots of data. using selenium.

**Comment by Didayolo** [comment]
@bbearce #1376 is deployed on production, let's see if it helps!

**Comment by Didayolo** [comment]
We need to make the loading of competition page lazy.

**Comment by ihsaan-ullah** [comment]
<img width="1273" alt="Screenshot 2024-11-03 at 2 58 55 PM" src="https://github.com/user-attachments/assets/53c18e16-bb0f-4c8f-b023-a1f3eaf8da97">

What do you think if we separate the admin procedures from the competition detail page? Similar to Edit page we can separate the submissions, participants etc in separate pages

**Comment by Didayolo** [comment]
That may be a good idea, especially for "Submissions" which can be heavy. However this will accelerate the loading only for organizers and admins.

**Comment by Didayolo** [comment]
We removed temporarily the submissions and participants counters to unblock the platform (#1646)

**Comment by ihsaan-ullah** [comment]
Here is what we want to do:

### Submissions and Participants
1. Put submissions and participants count in the competition model (update these counts when a new submission/ participant is added or a submission is deleted)
2. For all current competitions fill these fields with correct values
3. In the competition detail page, use these values in the UI (currently we show nothing)
4. In the home page make the popular competiitons dynamic again using the new participants count field

### Featured Competiitons on home page
1. Update the competition modal to have field/attribute `is_featured` that controls if a competition is featured or not
2. Use this field in the home page to show real featured competitions

### Home page counters
1. Update the counts somewhere in a file or in the db with a script that is run once a day
2. Update home page to fetch the counts from the file/db to make them dynamic instead of hardcoded

**Comment by Didayolo** [comment]
@ihsaan-ullah Just a quick note to remind ourselves that the submission counter is still not re-implemented on the leaderboard (always showing "1 entry")

**Comment by ObadaS** [comment]
We have decided to remove the column showing the number of entries in the leaderboard (which we disabled a while ago because of the performance issues it caused)
