### ISSUE TITLE
Task list paging / editing bug

### ISSUE THREAD

**Issue by johann-petrak** [codalab/codabench#1429]
# Todos

- [ ] On task update, stay on the current page
- [ ] On task create, go to first page
- [ ] On task upload, go to first page

***

Go to the list of tasks with Resources - then clicking on the Task tab.

If that list contains more entries, there will be a ">" button to scroll to page 2. 

Edit some task on page 2, then click update. 

You will see the list from page 1 again, but the scroll widget at the bottom shows "2" and only allows to scroll forward! 
![cb01](https://github.com/codalab/codabench/assets/619106/feda58bc-bf0c-4d86-9aef-a16962648c63)

When you now click on one of the task shown in the list to edit it, no error is shown, but the configuration for that task is shown as completely empty: 
![cb02](https://github.com/codalab/codabench/assets/619106/6f1a161e-4361-4539-9961-7c880da364bc)
This was very confusing because I thought originally my update has cleared the config for all my tasks when I checked!

It is even possible to scroll further: 
![cb03](https://github.com/codalab/codabench/assets/619106/77782dcb-fabe-4556-91fe-3b00f4bc0af7)
