### ISSUE TITLE
Dumps - Issues and TODO

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#724]
This issue regroups reported problems and future improvements of the "dump" features (download an existing competition as a bundle).

# BUGS

From #415:

Isabelle and Romain identified 3 bugs in dumps:

- [ ] People that are admins but NOT competition owners cannot create dumps
- [ ] There is no possibility to create a dump of competition that includes the task as a zip inside the competition bundle.
- [ ] Newly created dumps (e.g. today june 8, 2020) obtain the "wrong" date.

<img width="891" alt="Screen Shot 2020-06-08 at 9 17 05 AM" src="https://user-images.githubusercontent.com/7594063/84054853-d4cb2f00-a968-11ea-8b2a-8091cd94ba2a.png">
 in this example the date 2019-11-27 should be 2020-06-08

# TODO

- [ ] #373

- **Full style** dump would include all files in the zip

- **Key only style** dump would dump the dataset keys into the zip

Depends on #370

- #590

I.e., upload competition, dump it, recreate from dump, make submission

**Comment by ihsaan-ullah** [comment]
> People that are admins but NOT competition owners cannot create dumps

I have checked and an admin can create dump
<img width="1246" alt="Screenshot 2023-05-08 at 2 03 52 PM" src="https://user-images.githubusercontent.com/13259262/236783410-15cbc385-7bac-4a59-8948-dfd7a4737ebd.png">

**Comment by ihsaan-ullah** [comment]
@Didayolo I think this issue is handled
