### ISSUE TITLE
Transparency of docker images and scoring programs

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#764]
It is shown in #723 that the `starting kit` and `public data` buttons do not exist anymore in Codabench.

More generally, we would like to add a "transparency" feature. Organizers could have option to decide what they want to make public: the competition docker image, the scoring program, ingestion program, input data, etc.

Each piece made public would have a download button from the competition web pages.
The docker image could simply be shown using its DockerHub tag.

The sample submission (solution) should also be subject to this transparency, not only by being downloadable, but by being automatically run and evaluated.

The fact that CodaLab Competitions and Codabench are open-source is a crucial point in making these platforms great tools for the scientific community. This way, everybody can review the code and the benchmarks and competitions are more valuable.
However, the code and data used by the organizers is not necessarily open. Even if some organizers provide the code via Github with a link in the documentation, one can not ensure that it is really the code used to evaluate the submissions, making the final results less transparent. The goal of this feature is to have a real transparency, when enabled, between the organizers and the participants.

---

Similar ideas:

- **Organizers contact email**

It would be good to have a place, typically a field in the editor, for the organizer's email address. This is important because it is very common that participants contact the administrators of the platform instead of the organizers for competition specific questions because they can't find their contact.

Inside parenthesis next to "organized by":

<img width="617" alt="Capture d’écran 2023-06-22 à 17 04 56" src="https://github.com/codalab/codabench/assets/11784999/0a219f87-6fb9-4da8-96ec-c17ae387ee73">

A sentence in the forum:

<img width="771" alt="Capture d’écran 2023-06-22 à 17 05 03" src="https://github.com/codalab/codabench/assets/11784999/48c40beb-bed1-4d96-898c-5356d0b70808">

- **Link to the report**

It would be interesting to have a way to show the link to a competition report. The link could be accessible from an icon benchmark listing, and also well visible in the competition home page.

- **Reward (prize) of the competition**

As stated in #954, we should be able to set a reward (e.g. 4000$) from the editor. I don't think we want it to be doable from the competition.yaml file because that should be done only one the "production" version of the competition, after the tests. It could then be shown in the interface, in the home page of the challenge and in the public challenges list.

In the list:

<img width="864" alt="Capture d’écran 2023-06-16 à 12 38 01" src="https://github.com/codalab/codabench/assets/11784999/fe75eac0-26f0-4d30-9243-50fe81a3eb00">

Below "participants" and "submissions" using the same styling:

<img width="1031" alt="Capture d’écran 2023-06-16 à 12 38 12" src="https://github.com/codalab/codabench/assets/11784999/d7e89a01-e766-4e41-8028-9d0873519f96">

# TODOs:

#### Editor / YAML fields

- [x] Display docker image name in competition
Solved by: #944 
- [x] Add a YAML and editor field `Organizers contact` where the organizers put an email address that will be shown in the interface of the competition
Solved by: #1063
- [x] Editor field `Reward` (free-form string?)
Solved by: #1063
- [x] Editor field `Challenge report`
Solved by: #1063

#### Files tab

First PR #970:

- [x] For non-approved participants: Not accessible
- [x] For approved participants: Showing objects made available by organizers
- [x] For organizers: Showing all object and a column showing what is available or not to participants 

Next TODOs:

- [x] In editor / YAML, two options: make programs available, make input data available (#1136)
- [x] Add [documentation](https://github.com/codalab/codabench/wiki/Yaml-Structure) about the fields to add starting kit and public data in the file `competition.yaml`
- [x] Solutions appear even when not registered to the competition. Should be treated in the same way as public data and starting kit (show only to registered participants and organizers, and always in available state)
- [x] The `No Files Available Yet` text is always showing (#1041)
- [x] Fix the column `Available` that always displays "Yes" (see #970) (#1136)
- [x] Green checks instead of `yes` (see screenshot below, like the resources interface). These ticks are just markers and should not be clickable. (#1136)

<img width="183" alt="Capture d’écran 2023-07-25 à 17 50 29" src="https://github.com/codalab/codabench/assets/11784999/4ba8c540-4ee3-4816-bfe5-f4aea1c63fdb">

See the discussion below for better understanding

**Comment by Didayolo** [comment]
Similar ideas:

- Email organizers

It would be good to have a place (typically a field in the editor) for the organizer's email address.

- Link to the report  

It would be interesting to have a way to show the link to a competition report. The link could be accessible from the benchmark listing.

**Comment by ihsaan-ullah** [comment]
@Didayolo we should discuss this to make a plan for these features

**Comment by Didayolo** [comment]
@ihsaan-ullah Yes, I think some details should be discussed to agree on what we want to do. Also, it is important to discuss with Benjamin who is working on adding the "Files" tab to download data and starting kit.

**Comment by ihsaan-ullah** [comment]
@Didayolo Benjamin is working on download download buttons but the decision is not finalized yet about where to inject starting kit and sample submission

**Comment by Didayolo** [comment]
A good solution to how organizers can chose what is available for participants or not is to use the "files" tab for this:

<img width="500" alt="Capture d’écran 2023-06-14 à 15 32 59" src="https://github.com/codalab/codabench/assets/11784999/81fdb7c8-3f16-40bd-bd2e-cf530d7965a9">

This tab should be:

- Not accessible by non-approved participants
- Showing available objects to approved participants
- Showing all objects to organizers and having a column showing what is available or not to participants (and an option to chose to make available/unavailable each object).

**Comment by Didayolo** [comment]
For non-approved, we could have the same thing as the submissions tab:

<img width="1294" alt="Capture d’écran 2023-06-14 à 15 51 17" src="https://github.com/codalab/codabench/assets/11784999/3ed39a81-8ba5-40ba-869d-3b7aa91e5741">

(check the behavior when revoked, etc.)

**Comment by ihsaan-ullah** [comment]
@Didayolo 

> Add a yaml / editor field Organizers contact where the organizers put an email address that will be shown in the interface of the competition

Is this required? Normally we put contact info in the html/markdown pages

 
> Think about the possibility of having a Challenge report field or something

What is challenge report?

**Comment by Didayolo** [comment]
> Is this required? Normally we put contact info in the html/markdown pages

We need to think about it. The problem is that many organizers forget to put their contact in the documentation. Also, as it is free form, the contact info can be hard to find when it is somewhere.

> What is challenge report?

I was thinking about after the competition end: an analysis paper, or a blog post sharing the results, etc.

**Comment by ihsaan-ullah** [comment]
> We need to think about it. The problem is that many organizers forget to put their contact in the documentation. Also, as it is free form, the contact info can be hard to find when it is somewhere.

In this case this is useful. Some questions:

1. where will this be shown in the UI? Maybe a new tab about contact info?
2. do we just need email address or something else too?
3. In the editor: if we just need an email, this can be added in the main page where can add/edit Queue and docker. If we need more than just an email, then a separate tab

> I was thinking about after the competition end: an analysis paper, or a blog post sharing the results, etc.

should this be an html page or just one field where organizer can put a link. I think we should give multiple options if we are not providing html/markdown page. For example: link to 

- dataset
- paper
- blog

**Comment by Didayolo** [comment]
### Contact email

> where will this be shown in the UI? Maybe a new tab about contact info?

A new tab seems to be too much just for an email address, but it is a possibility.

> where will this be shown in the UI? Maybe a new tab about contact info?

I think a single email address is sufficient. If organizers want to provide more, they can still use the documentation.

> In the editor

Yes, it should be a simple field in the main page of the editor. Maybe there should be a warning or something showing that it is important to add a contact email.

### Report

> should this be an html page or just one field where organizer can put a link

I think a link is sufficient and gives enough freedom, it is good to keep it simple. Once again, organizers can still edit the documentation pages if they want to give more information. Here, the goal is to have an interface to redirect to the analysis. Typically, if the link to the report could be displayed in the [competition list interface](https://www.codabench.org/competitions/public/?page=1).

**Comment by ihsaan-ullah** [comment]
@Didayolo  What should be the name fo the report?

External link, Related paper, Related report or something else

**Comment by Didayolo** [comment]
Very good question.

Analysis paper, Challenge report ?

**Comment by ihsaan-ullah** [comment]
Challenge report seems reasonable. Lets use this for now and we can change it later if this is not what we want

**Comment by ihsaan-ullah** [comment]
@Didayolo 

>  Field Reward
Just one field for reward? What will happen when there are prizes for 1st 2nd 3rd positions?

**Comment by Didayolo** [comment]
@ihsaan-ullah We can discuss about it. In CodaLab we have just one field for the reward, that is usually used to show the **total reward**, so the addition of all prizes.

Note that this interface is just used to inform participants about the total prize. No money transfer is made from the platform.

**Comment by Didayolo** [comment]
🎉
