### ISSUE TITLE
Improve resources interface

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#841]
The interface for managing datasets, submissions and tasks could be improved.

- [ ] Add the size of the files
- [ ] Submission details: in which benchmark
- [ ] Submission: name it using the filename
- [ ] Have a separate tab for submissions #596
- [ ] Rename datasets tab #840
- [ ] A "progress bar" for the storage quota (#713)

As shown in the screenshot below, we can manage and remove submissions from the "resources" interface. However, we do not track what the benchmark on which the submission was made, so it is hard to know what we are removing.

<img width="1203" alt="Capture d’écran 2023-04-29 à 01 41 54" src="https://user-images.githubusercontent.com/11784999/235270510-c7deae62-2371-465f-a89b-86bd0d235d1f.png">

**Comment by Didayolo** [comment]
I merge this issue with the "Storage and clean up" one to keep track of everything in one place.
