### ISSUE TITLE
Rename the first "about codabench" block

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#949]
Just a post it to remember to rename this block:

<img width="647" alt="Capture d’écran 2023-06-15 à 15 29 31" src="https://github.com/codalab/codabench/assets/11784999/8c80285b-be4f-486d-9b9d-0b9a3e4b9dba">

<img width="294" alt="Screenshot 2023-06-15 at 7 07 19 PM" src="https://github.com/codalab/codabench/assets/13259262/ac607674-93c9-4cb4-b50d-915fe0545c16">

Change Github link from `https://github.com/codalab/competitions-v2` to `https://github.com/codalab/codabench`

Make `Popular Benchmarks` and `Featured Benchmarks` links to public benchmarks:

<img width="1063" alt="Capture d’écran 2023-06-15 à 16 28 28" src="https://github.com/codalab/codabench/assets/11784999/67afd271-67c5-4146-8e8e-5752504ee522">

# Todos

- [x] Rename `About Codabench` to `Get started`
- [x] Update codabench github link and tutorial link
- [x] Make `Popular Benchmarks` and `Featured Benchmarks` links that redirect to the competition lists (https://www.codabench.org/competitions/public/?page=1)

**Comment by Didayolo** [comment]
### Home page changes

Rename this block to `Get started`:

<img width="647" alt="Capture d’écran 2023-06-15 à 15 29 31" src="https://github.com/codalab/codabench/assets/11784999/8c80285b-be4f-486d-9b9d-0b9a3e4b9dba">

Rename the links from `competitions-v2`to `codabench`:

<img width="294" alt="Screenshot 2023-06-15 at 7 07 19 PM" src="https://github.com/codalab/codabench/assets/13259262/ac607674-93c9-4cb4-b50d-915fe0545c16">

Make `Popular Benchmarks` and `Featured Benchmarks` links to public benchmarks:

<img width="1063" alt="Capture d’écran 2023-06-15 à 16 28 28" src="https://github.com/codalab/codabench/assets/11784999/67afd271-67c5-4146-8e8e-5752504ee522">


Change Github link from `https://github.com/codalab/competitions-v2` to `https://github.com/codalab/codabench`

# Todos

- [ ] Rename `About Codabench` to `Get started`
- [ ] Update codabench github link and tutorial link
- [ ] Make `Popular Benchmarks` and `Featured Benchmarks` links that redirect to the competition lists (https://www.codabench.org/competitions/public/?page=1)
