### ISSUE TITLE
Phase status 

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#977]
In phase model, we have a field `status`. It is only updated when a new phase is added from the editor.
Phase status is determined from start date and end date of a phase in Phase Serializers.

The following should be changed.

# TODOs:

- [x] add `status` and `is_final_phase` a model property
- [x] remove `status` and `is_final_phase` (model filed)
- [x] remove adding status from adding new phase from editor
- [x] remove the logic of getting status from serializers
- [x] add the logic to model 
- [x] remove from auto_migrate phase
- [ ] test in detail

**Comment by Didayolo** [comment]
Continuation of #934

**Comment by Didayolo** [comment]
I don't, sorry.

**Comment by ihsaan-ullah** [comment]
To discuss: What will be the statuses for all these phases
- Phase0 (Ended) -> Previous?
- Phase1 (Ended) -> Previous?
- Phase2 (Ended) -> Previous?
- Phase3 (On going) -> Current?
- Phase4 (Not started) -> Next?
- Phase5 (Not started) -> Next?
- Phase6 (Not started) -> Next?

**Comment by ihsaan-ullah** [comment]
Closing this as this not needed
