### ISSUE TITLE
Improve forum UI

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#979]
Improvements of the forum interface

### Done (#1048)
- [x] Make front-end for pinning threads
- [x] Tiny profile pic next to the username
- [x] Improve styling (see comments in #601)
- [x] User email addresses should not be shown (solved by #929)
- [x] Fix delete button in forum thread (not showing for some reason)
- [x] Fix delete button in forum thread post (not showing for some reason)

### TODOs

- [x] Make usernames clickable
Solved by: #1112 
- [x] Show user profile image in forum
Solved by: #1113
- [x] "Add new post" button should be at the bottom, not at the top of the page?
Solved by: #1116

**Comment by ihsaan-ullah** [comment]
@Didayolo any suggestions

<img width="1209" alt="Screenshot 2023-06-24 at 1 31 24 AM" src="https://github.com/codalab/codabench/assets/13259262/8a119037-bc3b-4765-ab77-00f8f311b46d">

**Comment by ihsaan-ullah** [comment]
@Didayolo I think the last point is ok "Button at the top" because if a forum has many posts, this button will go down

> "Add new post" button should be at the bottom, not at the top of the page?
